publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "mrv1a_arm_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3"]
    pos1: [0.0, 0.0, 1.57, 0.0, 0.0, 0.0]
    pos2: [0.0, -0.2, 1.2, -0.785, 0.785, -1.0]
    pos3: [-0.785, 0.2, 2.0, 0.785, -0.785, 2.0]

    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
